baseURL = "https://cubes.sconeforgemystic.com/"
languageCode = "en-us"
title = "SconeforgeMystic's Cube Collection"
theme = "contrast-hugo"
enableEmoji = true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

[params]
minimal = false
description = "A collection of Magic: The Gathering cubes"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/"
weight = 10

# [[menu.main]]
# identifier = "cubes"
# name = "Cubes"
# url = "/cubes"
# weight = 20

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 30
